/* eslint-disable react/react-in-jsx-scope */
import type { NextPage } from 'next'
import Head from 'next/head'
import UploadNFTButton from '../../component/nft/UploadNft'

const Editor: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <UploadNFTButton/>
      </main>

      <footer></footer>
    </div>
  )
}

export default Editor
