'use client'
/* eslint-disable react/react-in-jsx-scope */
import type { NextPage } from 'next'
import Head from 'next/head'
import UE5 from '../../component/editor/UE5'
import styles from '../../styles/Home.module.css'

const Editor: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <UE5 />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Editor
